name: Documentation Issue
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Unclear/confusing documentation
        - Incorrect/outdated documentation
        - Typo or formatting issue
        - Broken link
        - Example/tutorial request
        - Translation issue
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue?
      options:
        - README.md (main repository page)
        - CHANGELOG.md
        - CONTRIBUTING.md
        - Installation instructions
        - Configuration guide
        - Troubleshooting guide
        - Issue templates
        - Other (specify below)
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL or Location
      description: Link to the documentation or describe where it is
      placeholder: "https://github.com/.../README.md or 'Installation section'"

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: Describe the documentation issue
      placeholder: "The documentation says... but it should say..."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: If applicable, suggest how to improve the documentation
      placeholder: "I suggest changing/adding..."

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context about the documentation issue
      placeholder: "This is confusing because..."
